# permissions to do viewer storeendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storeendpoint-viewer-role
rules:
- apiGroups:
  - monitoring.banzaicloud.io
  resources:
  - storeendpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.banzaicloud.io
  resources:
  - storeendpoints/status
  verbs:
  - get
