apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio
        args:
        - server
        - /storage
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
        - name: MINIO_ACCESS_KEY
          value: "minio_access_key"
        - name: MINIO_SECRET_KEY
          value: "minio_secret_key"
        - name: MINIO_REGION
          value: 'test_region'
        ports:
        - containerPort: 9000
---
kind: Service
apiVersion: v1
metadata:
  name: minio-service
  namespace: logging
spec:
  selector:
    app: minio
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
