apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: Receiver
metadata:
  name: receiver-sample
spec:
  receiverGroups:
    - name: tenant-a
      replicas: 2
      tenants: ["tenant-a"]
      config:
        mountFrom:
          secretKeyRef:
            name: thanos
            key: object-store.yaml
      dataVolume:
        pvc:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
      metrics:
        serviceMonitor: true
    - name: soft-tenant
      config:
        mountFrom:
          secretKeyRef:
            name: thanos
            key: object-store.yaml
      dataVolume:
        pvc:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
      metrics:
        serviceMonitor: true
      httpIngress: {}
---
apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: Thanos
metadata:
  name: receiver-sample-query
spec:
  query:
    metrics:
      serviceMonitor: true
    stores:
    - "dnssrv+_grpc._tcp.receiver-sample-receiver-soft-tenant"
    - "dnssrv+_grpc._tcp.receiver-sample-receiver-tenant-a"
    queryReplicaLabel:
    - replica
    - receive_replica
    grafanaDatasource: true