apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: StoreEndpoint
metadata:
  name: storeendpoint-sample
spec:
  # Add fields here
  config:
    mountFrom:
      secretKeyRef:
        name: thanos
        key: object-store.yaml
  #selector: {}
