apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: Thanos
metadata:
  name: thanos-sample
spec:
  enableRecreateWorkloadOnImmutableFieldChange: true
  query:
    metrics:
      serviceMonitor: true
    ingress: {}
  rule:
    dataVolume:
      pvc:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          volumeMode: "Filesystem"
  storeGateway:
    metrics:
      serviceMonitor: true


---

apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: Thanos
metadata:
  name: query
spec:
  # Add fields here
  query: {}
  queryDiscovery: true