apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: Receiver
metadata:
  name: receiver-sample
spec:
  receiverGroups:
    - name: tenant-a
      replicas: 2
      tenants: ["tenant-a"]
      config:
        mountFrom:
          secretKeyRef:
            name: thanos
            key: object-store.yaml
      dataVolume:
        pvc:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
      metrics:
        serviceMonitor: true
    - name: soft-tenant
      config:
        mountFrom:
          secretKeyRef:
            name: thanos
            key: object-store.yaml
      dataVolume:
        pvc:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
      metrics:
        serviceMonitor: true
      httpIngress: {}