
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: storeendpoints.monitoring.banzaicloud.io
spec:
  group: monitoring.banzaicloud.io
  names:
    kind: StoreEndpoint
    listKind: StoreEndpointList
    plural: storeendpoints
    singular: storeendpoint
  scope: ""
  validation:
    openAPIV3Schema:
      description: StoreEndpoint is the Schema for the storeendpoints API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: StoreEndpointSpec defines the desired state of StoreEndpoint
          properties:
            config:
              properties:
                mountFrom:
                  description: Refers to a secret value to be used through a volume
                    mount
                  properties:
                    secretKeyRef:
                      description: SecretKeySelector selects a key of a Secret.
                      properties:
                        key:
                          description: The key of the secret to select from.  Must
                            be a valid secret key.
                          type: string
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                        optional:
                          description: Specify whether the Secret or its key must
                            be defined
                          type: boolean
                      required:
                      - key
                      type: object
                  type: object
                value:
                  description: Refers to a non-secret value
                  type: string
                valueFrom:
                  description: Refers to a secret value to be used directly
                  properties:
                    secretKeyRef:
                      description: SecretKeySelector selects a key of a Secret.
                      properties:
                        key:
                          description: The key of the secret to select from.  Must
                            be a valid secret key.
                          type: string
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                        optional:
                          description: Specify whether the Secret or its key must
                            be defined
                          type: boolean
                      required:
                      - key
                      type: object
                  type: object
              type: object
            selector:
              properties:
                annotations:
                  additionalProperties:
                    type: string
                  type: object
                grpcPort:
                  format: int32
                  type: integer
                httpPort:
                  format: int32
                  type: integer
                labels:
                  additionalProperties:
                    type: string
                  type: object
                namespaces:
                  type: string
              type: object
            thanos:
              type: string
            url:
              description: Foo is an example field of StoreEndpoint. Edit StoreEndpoint_types.go
                to remove/update
              type: string
          required:
          - thanos
          type: object
        status:
          description: StoreEndpointStatus defines the observed state of StoreEndpoint
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
